AISDK-169: Add transcriber and start ts
revdotcom/revai-java-sdk pull request #30
Opened 2022-01-26 06:45 UTC by Chanc3

2022-01-26 17:11 UTC, k-weng requested changes
Few comments but overall looks good, will need to update package version (I think)

2022-01-26 17:11 UTC, k-weng commented on src/main/java/ai/rev/speechtotext/StreamingClient.java
> +      }
are we using 2-space indents? If so
```suggestion
        urlBuilder.addQueryParameter(
          "start_ts", String.valueOf(sessionConfig.getStartTs()));
      }
```

2022-01-26 17:11 UTC, k-weng commented on src/main/java/ai/rev/speechtotext/StreamingClient.java
> +      }
```suggestion
        urlBuilder.addQueryParameter(
          "transcriber", sessionConfig.getTranscriber());
      }
```

2022-01-26 17:11 UTC, k-weng commented on src/test/java/ai/rev/speechtotext/unit/RevAiStreamingClientOptionalParametersTest.java
> +              .contains("start_ts=" + sessionConfig.getStartTs());
Don't think this needs two lines
```suggestion
      assertThat(request.getPath()).contains("start_ts=" + sessionConfig.getStartTs());
```
But if two lines is wanted, will need proper indentation
```suggestion
      assertThat(request.getPath())
        .contains("start_ts=" + sessionConfig.getStartTs());
```

2022-01-26 17:11 UTC, k-weng commented on src/test/java/ai/rev/speechtotext/unit/RevAiStreamingClientOptionalParametersTest.java
> +    }
Same comment as above

2022-01-26 19:07 UTC, kbridbur commented on examples/StreamingFromLocalFile.java
> +    sessionConfig.setTranscriber("machine_v2");
Same comment as on the node sdk. This should not be the default for the example

2022-01-27 15:50 UTC, kbridbur approved these changes

2022-01-27 15:57 UTC, k-weng approved these changes

2022-01-27 15:58 UTC, merged